# Generated by Django 3.0.4 on 2020-03-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200321_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='deleted',
        ),
        migrations.AddField(
            model_name='post',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
